# Generated by Django 5.2.2 on 2025-11-24 11:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0002_addingcalculation_volumeweightcalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='DensityTemperatureCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_density_kg_m3', models.FloatField(help_text='Измеренная плотность при текущей температуре', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Фактическая плотность (кг/м³)')),
                ('reference_temperature_c', models.FloatField(verbose_name='Текущая температура (°C)')),
                ('target_temperature_c', models.FloatField(verbose_name='Целевая температура (°C)')),
                ('thermal_expansion_coefficient', models.FloatField(default=0.00065, help_text='Типовое значение для нефтепродуктов — 0.00065', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Коэффициент объемного расширения (1/°C)')),
                ('corrected_density_kg_m3', models.FloatField(default=0.0, verbose_name='Плотность при целевой температуре (кг/м³)')),
                ('density_difference_kg_m3', models.FloatField(default=0.0, verbose_name='Изменение плотности (кг/м³)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время расчета')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calibration.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Расчет плотности по температуре',
                'verbose_name_plural': 'Расчеты плотности по температуре',
                'ordering': ['-timestamp'],
            },
        ),
    ]
