# Generated by Django 5.1.7 on 2025-11-26 12:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0003_densitytemperaturecalculation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasolineBlendCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_octane', models.IntegerField(help_text='Желаемое октановое число смеси (например: 80, 92, 95, 98, 100)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Целевое октановое число')),
                ('target_price', models.DecimalField(blank=True, decimal_places=2, help_text='Опционально: желаемая цена за литр для оптимизации', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Целевая цена (сум/литр)')),
                ('total_volume_liters', models.DecimalField(blank=True, decimal_places=2, help_text='Опционально: общий объем смеси для расчета полной стоимости', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Общий объем (литры)')),
                ('calculation_method', models.CharField(choices=[('linear', 'Линейная интерполяция'), ('weighted', 'Взвешенная'), ('research', 'Research метод')], default='linear', help_text='Метод расчета октанового числа смеси', max_length=20, verbose_name='Метод расчета')),
                ('variants_count', models.IntegerField(default=5, help_text='Сколько вариантов смесей показывать (1-20)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Количество вариантов')),
                ('blend_variants', models.JSONField(default=list, help_text='JSON структура с вариантами смесей', verbose_name='Варианты смесей')),
                ('best_variant_index', models.IntegerField(default=0, help_text='Индекс варианта с наилучшей ценой', verbose_name='Индекс лучшего варианта')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время расчета')),
            ],
            options={
                'verbose_name': 'Расчет бензиновой смеси',
                'verbose_name_plural': 'Расчеты бензиновых смесей',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='gost_percentage',
            field=models.FloatField(blank=True, help_text='Процент использования продукта в смеси согласно ГОСТ стандартам (0-100%)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='GOST процент (%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_blending',
            field=models.BooleanField(default=True, help_text='Можно ли использовать этот продукт для создания бензиновых смесей', verbose_name='Используется для смешивания'),
        ),
        migrations.AddField(
            model_name='product',
            name='octane_number',
            field=models.IntegerField(blank=True, help_text='Октановое число продукта (например: 48, 52, 60, 80, 92, 95, 98, 100)', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Октановое число'),
        ),
        migrations.AddField(
            model_name='product',
            name='price_per_liter',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Цена продукта за один литр в сумах', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена за литр (сум)'),
        ),
    ]
