# Generated by Django 5.1.7 on 2025-11-26 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0004_gasolineblendcalculation_product_gost_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProductConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Konfiguratsiya', help_text='Saqlangan konfiguratsiya nomi', max_length=200, verbose_name='Nomi')),
                ('products_config', models.JSONField(default=dict, help_text='JSON struktura: {product_id: {octane, price, gost_percentage, ...}}', verbose_name='Productlar konfiguratsiyasi')),
                ('description', models.TextField(blank=True, help_text="Qo'shimcha ma'lumot", null=True, verbose_name='Tavsif')),
                ('is_active', models.BooleanField(default=True, help_text='Ushbu konfiguratsiya faolmi?', verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan vaqti')),
            ],
            options={
                'verbose_name': 'Saqlangan product konfiguratsiyasi',
                'verbose_name_plural': 'Saqlangan product konfiguratsiyalari',
                'ordering': ['-created_at'],
            },
        ),
    ]
