# Generated by Django 5.2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0005_savedproductconfiguration'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_date', models.DateField(help_text='Дата расчета', verbose_name='Дата расчета')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0, help_text='Цена продажи', max_digits=12, verbose_name='ПРОДАЖА (цена)')),
                ('materials', models.JSONField(default=list, help_text='JSON структура с материалами: [{name, octane, price, percentage, octanePercent, cost}, ...]', verbose_name='Материалы')),
                ('total_percentage', models.FloatField(default=0, help_text='Сумма всех процентов', verbose_name='Общий процент (%)')),
                ('total_octane_percent', models.FloatField(default=0, help_text='Сумма всех ОКТАН * %', verbose_name='ОКТАН * % (итого)')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, help_text='Сумма всех себестоимостей', max_digits=12, verbose_name='СЕБЕСТОИМОСТ (итого)')),
                ('total_profit', models.DecimalField(decimal_places=2, default=0, help_text='Прибыль = ПРОДАЖА - СЕБЕСТОИМОСТ', max_digits=12, verbose_name='ПРЫБЛ (прибыль)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Время расчета')),
            ],
            options={
                'verbose_name': 'Расчет переработки',
                'verbose_name_plural': 'Расчеты переработки',
                'ordering': ['-timestamp'],
            },
        ),
    ]
