# Generated by Django 5.2.2

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0006_processingcalculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_for_processing',
            field=models.BooleanField(default=False, help_text='Показывать ли этот продукт в калькуляторе переработки', verbose_name='Используется для переработки'),
        ),
    ]
