# Generated by Django 5.1.7 on 2026-02-23 09:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0007_add_is_for_processing_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specific_weight_kg_per_liter',
            field=models.FloatField(blank=True, help_text='Удельный вес продукта в кг/л (например: 0.74 для бензина, 0.83 для дизеля)', null=True, validators=[django.core.validators.MinValueValidator(0.0001)], verbose_name='Удельный вес (кг/л)'),
        ),
    ]
