# Generated by Django 5.1.7 on 2026-02-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calibration', '0008_add_specific_weight_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='processing_order',
            field=models.PositiveIntegerField(default=0, help_text='Порядок отображения в калькуляторе (1 — первый, 2 — второй и т.д.)', verbose_name='Порядок в калькуляторе переработки'),
        ),
    ]
